//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernBrowserShim.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernBrowserShim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HEAD&gt;
        ///&lt;STYLE&gt;BODY {
        ///	FONT-FAMILY: Verdana; MARGIN-TOP: 0px; COLOR: #000000; TEXT-ALIGN: left; MARGIN-LEFT: 0px; BACKGROUND-COLOR: white
        ///}
        ///#content {
        ///	FONT-SIZE: 0.7em; PADDING-BOTTOM: 2em; MARGIN-LEFT: 30px
        ///}
        ///A:link {
        ///	TEXT-DECORATION: underline; FONT-WEIGHT: bold; COLOR: #336699
        ///}
        ///A:visited {
        ///	TEXT-DECORATION: underline; FONT-WEIGHT: bold; COLOR: #6699cc
        ///}
        ///A:active {
        ///	TEXT-DECORATION: underline; FONT-WEIGHT: bold; COLOR: #336699
        ///}
        ///A:hover {
        ///	TEXT-DECORATION: underline; FONT-WEIGHT: bold;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutScript {
            get {
                return ResourceManager.GetString("AboutScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (async function(){ await CefSharp.BindObjectAsync(&quot;SCSApplication&quot;); await CefSharp.BindObjectAsync(&quot;SCSGeneral&quot;); window.SCS = { Application:SCSApplication, General:SCSGeneral };})();.
        /// </summary>
        internal static string SCSBindScript {
            get {
                return ResourceManager.GetString("SCSBindScript", resourceCulture);
            }
        }
    }
}
